"""
vulnalyzer.graph.patch_request
===============================
Generates automated patch-request issue text for repository maintainers.

Given a scan result or a repo URL, produces a ready-to-post GitHub issue
body describing the vulnerable dependencies, CVE details, and suggested
remediation steps.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from vulnalyzer.scanner.engine import ScanResult, Finding


_SEVERITY_EMOJI = {
    "CRITICAL": "🔴",
    "HIGH":     "🟠",
    "MEDIUM":   "🟡",
    "LOW":      "🟢",
    "UNKNOWN":  "⚪",
}


def _severity_icon(severity: str) -> str:
    return _SEVERITY_EMOJI.get(severity.upper(), "⚪")


def generate_issue_body(scan_result: "ScanResult") -> str:
    """
    Generate a GitHub issue body for a maintainer describing all
    vulnerable dependencies found in *scan_result*.
    """
    now = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")

    # Group findings by package
    by_package: dict[str, list["Finding"]] = {}
    for f in scan_result.findings:
        key = f"{f.package_name}@{f.version_found} ({f.ecosystem})"
        by_package.setdefault(key, []).append(f)

    lines: list[str] = []

    lines.append("## 🔐 Vulnerable Dependency Report")
    lines.append("")
    lines.append(
        f"> Generated by [Vulnalyzer](https://github.com/your-org/vulnalyzer) "
        f"on {now} — scanned commit `{scan_result.revision_id[:12]}` "
        f"on branch `{scan_result.branch_ref}`."
    )
    lines.append("")

    if not scan_result.findings:
        lines.append("No vulnerabilities found in this scan. ✅")
        return "\n".join(lines)

    # Summary table
    counts = scan_result.severity_counts
    lines.append("### Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW", "UNKNOWN"):
        if counts.get(sev, 0):
            lines.append(f"| {_severity_icon(sev)} {sev} | {counts[sev]} |")
    lines.append("")

    # Detail per vulnerable package
    lines.append("### Vulnerable Dependencies")
    lines.append("")

    for pkg_key, findings in by_package.items():
        f0 = findings[0]
        dep_type = "direct" if f0.is_direct else "transitive"
        icon = _severity_icon(max(
            (f.severity for f in findings),
            key=lambda s: {
                "UNKNOWN": 0,
                "LOW": 1,
                "MODERATE": 2,
                "MEDIUM": 2,
                "HIGH": 3,
                "CRITICAL": 4,
            }.get((s or "UNKNOWN").upper(), 0),
        ))
        lines.append(f"#### {icon} `{pkg_key}` ({dep_type}, via `{f0.manifest_source}`)")
        lines.append("")
        for f in findings:
            fix_str = (
                f"Upgrade to `{f.fixed_versions[0]}`" if f.fixed_versions
                else "No fixed version known yet — monitor upstream"
            )
            lines.append(f"- **{f.osv_id}** {_severity_icon(f.severity)} `{f.severity}`")
            lines.append(f"  - {f.summary}")
            lines.append(f"  - 🔧 {fix_str}")
            lines.append(f"  - 🔗 https://osv.dev/vulnerability/{f.osv_id}")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("### How to fix")
    lines.append("")
    lines.append("Please update the affected packages to their patched versions listed above.")
    lines.append("If no fix is available yet, consider:")
    lines.append("")
    lines.append("- Pinning to the last unaffected version")
    lines.append("- Applying a virtual patch / WAF rule")
    lines.append("- Monitoring the advisory for updates")
    lines.append("")
    lines.append(
        "_This issue was automatically generated by "
        "[Vulnalyzer](https://github.com/your-org/vulnalyzer). "
        "Please close it once remediation is complete._"
    )

    return "\n".join(lines)


def generate_issue_title(scan_result: "ScanResult") -> str:
    counts = scan_result.severity_counts
    sev_summary = ", ".join(
        f"{counts[s]} {s.lower()}"
        for s in ("CRITICAL", "HIGH", "MEDIUM", "LOW")
        if counts.get(s, 0)
    ) or "unknown severity"
    return (
        f"[Vulnalyzer] Vulnerable dependencies detected — "
        f"{len(scan_result.findings)} finding(s) ({sev_summary})"
    )
